test:
  user:
    username: zhangsan
    age: 18
    toString: the age of  ${test.user.username} is ${test.user.age}
    
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test1
    username: root
    password: 123456

mybatis:
    mapper-locations: classpath:mybatis/dao/*.xml
    config-location: classpath:mybatis/mybatis-config.xml
    
